# prefix settings
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# window and pane settings
bind c new-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# bell settings
set -g bell-action any
set -g visual-bell on
set -g monitor-bell on

# others
bind S choose-session
set -g mode-keys vi
set -g set-clipboard on
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"
