# prefix settings
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# split-window settings
bind v split-window -h
bind s split-window -v

# select-pane settings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# choose-session settings
bind S choose-session
