# prefix settings
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# window settings
bind c new-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# select-pane settings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# choose-session settings
bind S choose-session
